passportfridays/urls.py
from django.conf.urls import patterns, include, url
from flights.views import Index, Detail, Contact, Filter, Notifications, SignIn, SignUp, SignOut
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from flights.api import QPXResource, SliceResource
from location.api import CityResource, CountryResource, CurrencyResource
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', Index.as_view(), name='index'),
    url(r'^contact$', Contact.as_view(), name='contact'),
    url(r'^notifications$', Notifications.as_view(), name='notifications'),
    url(r'^(?P<pk>\d+)/$', Detail.as_view(), name='detail'),
    url(r'^price/(?P<price>\d+)/$', Filter.as_view(), name='filter'),
    url(r'^signin/$', SignIn.as_view(), name='signin'),
    url(r'^signup/$', SignUp.as_view(), name='signup'),
    url(r'^price/(?P<price>\d+)/$', Filter.as_view(), name='filter'),
    url(r'^leaving-date/(?P<leavingDate>[0-9\-_]+)/$', Filter.as_view()),
    url(r'^city/(?P<city>[A-z]+)/$', Filter.as_view()),
    url(r'^signout/$', SignOut.as_view()),
    url(r'^api/qpx/', include(QPXResource.urls())),
    url(r'^api/slices/', include(SliceResource.urls())),
    url(r'^api/currenies/', include(CurrencyResource.urls())),
    url(r'^api/countries/', include(CountryResource.urls())),
    url(r'^api/cities/', include(CityResource.urls())),
    url(r'^thanks',TemplateView.as_view(template_name='flights/generic.html'),name='thanks'),
    url(r'^account',login_required(TemplateView.as_view(template_name='flights/generic.html')),name='thanks'),

 ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

flights/models.py
from django.db import models
from location.models import City, Country, Currency
from weekend.models import Dates
from django.utils import timezone


class Airport(models.Model):
    name = models.CharField(blank=True, null=True, max_length=75)
    city = models.ForeignKey(City)
    country = models.ForeignKey(Country)
    iata = models.CharField(blank=True, null=True, max_length=10)
    icao = models.CharField(blank=True, null=True, max_length=10)
    latitude = models.DecimalField(max_digits=10, decimal_places=6)
    longitude = models.DecimalField(max_digits=10, decimal_places=6)
    altitude = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    timezone = models.DecimalField(max_digits=4, decimal_places=2, default=0)

    def __unicode__(self):
        return '%s' % self.name

class Flight(models.Model):
    departure_airport = models.ForeignKey(Airport, related_name='departure_airport')
    arrival_airport = models.ForeignKey(Airport, related_name='arrival_airport')
    departure_time = models.DateTimeField(blank=True, null=True)
    arrival_time = models.DateTimeField(blank=True, null=True)
    flight_no = models.IntegerField(blank=True, null=True)
    carrier_code = models.CharField(max_length=5, blank=True, null=True)
    # arrival_date = models.DateTimeField(blank=True, null=True)
    stops = models.IntegerField(blank=True, null=True, default=0)

    def get_outbound_flights(self):
        return Flight.objects.filter(departure_airport=self.departure_airport)

    def get_inbound_flights(self):
        return Flight.objects.filter(arrival_airport=self.arrival_airport)

    def __unicode__(self):
        return '%s %s' % (self.carrier_code, self.flight_no)

class Slice(models.Model):
    """Only one slice per date per origin-destination pair should be in the DB at any one time,
        this is to ensure that we are not giving old quotes to customers"""
    dates = models.ForeignKey(Dates)
    origin = models.ForeignKey(City, related_name='origin city')
    price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    currency = models.ForeignKey(Currency)
    destination = models.ForeignKey(City, related_name='destination city')
    outbound_flight = models.ForeignKey(Flight, related_name='departing flight')
    inbound_flight = models.ForeignKey(Flight, related_name='return flight')
    quote_time = models.DateTimeField(default=timezone.now())

    @property
    def time_before_flight(self):
        return self.outbound_flight.departure_time - self.quote_time

    def save(self, *args, **kwags):
        self.quote_time = timezone.now()
        super(Slice, self).save(*args, **kwags)

    class Meta:
        ordering = ['price']

    def __unicode__(self):
        return self.origin.name

class HistoricSlice(models.Model):
    """Before a new Slice is saved into the DB a copy of the old one is saved into this model.
        This is to give us historic data to be able to track when flight prices change"""
    dates = models.ForeignKey(Dates)
    origin = models.ForeignKey(City, related_name='historic origin city')
    price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    currency = models.ForeignKey(Currency)
    destination = models.ForeignKey(City, related_name='historic destination city')
    outbound_flight = models.ForeignKey(Flight, related_name='historic departing flight')
    inbound_flight = models.ForeignKey(Flight, related_name='historic return flight')
    quote_time = models.DateTimeField(default=timezone.now())

    def save(self, *args, **kwags):
        self.quote_time = timezone.now()
        super(HistoricSlice, self).save(*args, **kwags)

    @property
    def time_before_flight(self):
        return self.outbound_flight.departure_time - self.quote_time

flights/forms.py
from django import forms
from .tasks import send_email
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from email_user.models import EmailUser

class ContactForm(forms.Form):
    name = forms.CharField()
    email =forms.EmailField()
    subject = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        data = self.cleaned_data
        send_email.delay('flights/emails/thanks_for_getting_in_contact.html',
                        {'name': data['name'],
                         'subject': data['subject']},
                        [data['email'],],
                        "Thanks for getting in contact")
        send_email('flights/emails/new_message.html',
            {'from_name': data['name'],
             'from_address': data['email'],
             'subject': data['subject'],
             'message': data['message']}
                [settings.DEFAULT_TO_EMAIL],
            'A new contact form')


class NotificationForm(forms.Form):
    max_price = forms.IntegerField()
    email = forms.EmailField()
    name = forms.CharField(max_length=200)
    OPTIONS = (
                ("AUT", "Australia"),
                ("DEU", "Germany"),
                ("NLD", "Neitherlands"),
                )
    countries = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=OPTIONS)

    def send_email(self):
        data = self.cleaned_data
        send_email('flights/emails/set_up_notifications.html',
                   {'name': data['name'],
                    'max_price': data['max_price'],
                    'countries': data['countries']},
                    [data['email'],],
                    'You have set up a new Notification',)

class EmailSignUpForms(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = EmailUser
        exclude =('username',)

flights/views.py
from .models import Slice
from django.views.generic import ListView, DetailView, FormView, View
from datetime import datetime, timedelta
from .forms import ContactForm, NotificationForm
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
from django.views.decorators.debug import sensitive_post_parameters
from django.utils.decorators import method_decorator
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from email_user.forms import EmailUserCreationForm
from email_user.models import EmailUser
from django.contrib.auth.forms import UserCreationForm
from .forms import EmailSignUpForms



class Index(ListView):

    context_object_name = 'slices'
    queryset = Slice.objects.order_by('destination', 'price', 'dates').distinct('destination')
    # queryset = Slice.objects.values_list('destination', 'dates').distinct('destination', 'dates')
    template_name = "flights/home.html"
    paginate_by = 10


class Filter(ListView):

    #context_object_name = 'slices'
    template_name = 'flights/home.html'
    pageinate_by =10
    model = Slice

    def get_context_data(self, **kwargs):
        context = super(Filter, self).get_context_data(**kwargs)
        if 'price' in self.kwargs:
            print self.kwargs['price']
            context['title'] = 'filtered on price'
            context['slices'] = Slice.objects.order_by('dates', 'destination').distinct('dates', 'destination')

        if 'leavingDate' in self.kwargs:
            date_object = datetime.strptime(self.kwargs['leavingDate'], '%Y-%m-%d')
            next_day = date_object + timedelta(days=+1)
            print next_day
            context['title'] = 'filtered by weekend'
            context['slices'] = Slice.objects.filter(outbound_flights__departure_time__gt=date_object,
                                                     outbound_flights__departure_time__lt=next_day).order_by('outbound_flights__price')
        if 'city' in self.kwargs:
            context['routes'] = Slice.objects.filter(airport__city__name=self.kwargs['city'])
        return context


class Detail(DetailView):
    model = Slice
    template_name = "flights/detail.html"

    def get_context_data(self, **kwargs):
        context = super(Detail, self).get_context_data(**kwargs)


class Contact(FormView):
    template_name = 'flights/contact.html'
    form_class = ContactForm
    success_url = '/thanks/'

    def form_valid(self, form):
        form.send_email()
        return super(Contact, self).form_valid(form)

class Notifications(FormView):
    template_name = 'flights/notifications.html'
    form_class = NotificationForm
    success_url = '/thanks/'

    def form_valid(self, form):
        form.send_email()
        return super(Notifications, self).form_valid(form)

class SignIn(FormView):
    form_class = AuthenticationForm
    template_name = 'flights/signin.html'

    def form_valid(self, form):
        redirect_to = settings.LOGIN_REDIRECT_URL
        login(self.request, form.get_user())
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
        return HttpResponseRedirect(redirect_to)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    @method_decorator(sensitive_post_parameters('password'))
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        return super(SignIn, self).dispatch(request, *args, **kwargs)

class SignOut(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(settings.LOGOUT_REDIRECT_URL)


class SignUp(FormView):
    template_name = 'flights/signup.html'
    form_class = EmailUserCreationForm
    success_url='/account'

    def form_valid(self, form):
        #call the save function to save the new user
        form.save()
        # form.send_email()
        #get the username and password
        username = self.request.POST['email']
        password = self.request.POST['password1']
        #authenticate user then login
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super(SignUp, self).form_valid(form)

templates/flights/base.html
<!DOCTYPE HTML>
<!--
	Alpha by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
        {% load staticfiles %}

		<title>Contact - Alpha by HTML5 UP</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<!--[if lte IE 8]><script src="css/ie/html5shiv.js"></script><![endif]-->
		<script src={% static "js/jquery.min.js" %}></script>
		<script src={% static "js/jquery.dropotron.min.js" %}></script>
		<script src={% static "js/jquery.scrollgress.min.js" %}></script>
		<script src={% static "js/skel.min.js" %}></script>
		<script src={% static "js/skel-layers.min.js" %}></script>
		<script src={% static "js/init.js" %}></script>
        <link rel="stylesheet" href={% static "css/style.css" %}/>
		<link rel="stylesheet" href={% static "css/style-wide.css" %}/>
		<noscript>
			<link rel="stylesheet" href={% static "css/skel.css" %}/>
		</noscript>
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
	</head>
	<body>
		<!-- Header -->
			<header id="header" class="skel-layers-fixed">
				<h1><a href="/">Passport Fridays</a></h1>
				<nav id="nav">
					<ul>
						<li>
							<a href="" class="icon fa-angle-down">Layouts</a>
							<ul>
								<li><a href="contact">Contact</a></li>
								<li><a href="notifications">Notifications</a></li>
								<li><a href="about">About</a></li>
								<li><a href="/signout">sign outt</a></li>
								<li>
									<!--<a href="">Submenu</a>
									<ul>
										<li><a href="#">Option One</a></li>
										<li><a href="#">Option Two</a></li>
										<li><a href="#">Option Three</a></li>
										<li><a href="#">Option Four</a></li>
									</ul>-->
								</li>
							</ul>
						</li>
						<li><a href="/signin" class="button">Sign In</a></li>
					</ul>
				</nav>
			</header>
            {% block content %}{% endblock %}
    </body>
</html>
<footer id="footer">
				<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
					<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
					<li><a href="#" class="icon fa-google-plus"><span class="label">Google+</span></a></li>
				</ul>
				<ul class="copyright">
					<li>© Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li><li>Demo Images: <a href="http://unsplash.com">Unsplash</a></li>
				</ul>
			</footer>

templates/flights/contact.html
{% extends 'flights/base.html' %}
{% block content %}
		<!-- Header -->
			<header id="header" class="skel-layers-fixed">
				<h1><a href="index.html">Alpha</a> by HTML5 UP</h1>
				<nav id="nav">
					<ul>
						<li><a href="index.html">Home</a></li>
						<li>
							<a href="" class="icon fa-angle-down">Layouts</a>
							<ul>
								<li><a href="generic.html">Generic</a></li>
								<li><a href="contact.html">Contact</a></li>
								<li><a href="elements.html">Elements</a></li>
								<li>
									<a href="">Submenu</a>
									<ul>
										<li><a href="#">Option One</a></li>
										<li><a href="#">Option Two</a></li>
										<li><a href="#">Option Three</a></li>
										<li><a href="#">Option Four</a></li>
									</ul>
								</li>
							</ul>
						</li>
						<li><a href="#" class="button">Sign Up</a></li>
					</ul>
				</nav>
			</header>

		<!-- Main -->
			<section id="main" class="container 75%">
				<header>
					<h2>Contact Us</h2>
					<p>Tell us what you think about our little operation.</p>
				</header>
				<div class="box">
					<form method="post" action="#">{% csrf_token %}
						<div class="row uniform 50%">
							<div class="6u 12u(mobilep)">
								<input type="text" name="name" id="id_name" value="" placeholder="Name" />
							</div>
							<div class="6u 12u(mobilep)">
								<input type="email" name="email" id="id_email" value="" placeholder="Email" />
							</div>
						</div>
						<div class="row uniform 50%">
							<div class="12u">
								<input type="text" name="subject" id="id_subject" value="" placeholder="Subject" />
							</div>
						</div>
						<div class="row uniform 50%">
							<div class="12u">
								<textarea name="message" id="id_message" placeholder="Enter your message" rows="6" ></textarea>
							</div>
						</div>
						<div class="row uniform">
							<div class="12u">
								<ul class="actions align-center">
									<li><input type="submit" value="Send Message" /></li>
								</ul>
							</div>
						</div>
					</form>
				</div>
			</section>

{% endblock %}

templates/flights/detail.html
{% extends 'flights/base.html' %}
{% block content %}
<header>
<h1>{{ title }}</h1>
</header>



<h3>{{ route.airport }}</h3>
<h4>Outbound Flights</h4>
{% for flight in route.outbound_flights.all %}
    <li>From: {{ flight.departure_airport }}</li>
    <li>{{ flight.carrier_code }} {{ flight.flight_no }}</li>
    <li>{{ flight.departure_time }}</li>
    <li>To: {{ flight.arrival_airport }}</li>
{%  endfor %}
<h4>Inbound Flights</h4>
{% for flight in route.inbound_flights.all %}
    <li>From: {{ flight.departure_airport }}</li>
    <li>{{ flight.carrier_code }} {{ flight.flight_no }}</li>
    <li>{{ flight.departure_time }}</li>
    <li>To: {{ flight.arrival_airport }}</li>
{%  endfor %}
{% endblock %}

templates/flights/generic.html
{% extends 'flights/base.html' %}
{% block content %}

		<!-- Main -->
			<section id="main" class="container">
				<header>
					<h2>Generic</h2>
					<p>A generic page for every non-generic situation.</p>
                    {% if user.is_authenticated %}
                        <p>{{ user.username }}</p>
                        <h1>{{ user.email }}</h1>
                    {% endif %}
				</header>
				<div class="box">
					<span class="image featured"><img src="images/pic01.jpg" alt="" /></span>
					<h3>This is a subheading</h3>
					<p>Cep risus aliquam gravida cep ut lacus amet. Adipiscing faucibus nunc placerat. Tempus adipiscing turpis non blandit accumsan eget lacinia nunc integer interdum amet aliquam ut orci non col ut ut praesent. Semper amet interdum mi. Phasellus enim laoreet ac ac commodo faucibus faucibus. Curae ante vestibulum ante. Blandit. Ante accumsan nisi eu placerat gravida placerat adipiscing in risus fusce vitae ac mi accumsan nunc in accumsan tempor blandit aliquet aliquet lobortis. Ultricies blandit lobortis praesent turpis. Adipiscing accumsan adipiscing adipiscing ac lacinia cep. Orci blandit a iaculis adipiscing ac. Vivamus ornare laoreet odio vis praesent nunc lorem mi. Erat. Tempus sem faucibus ac id. Vis in blandit. Nascetur ultricies blandit ac. Arcu aliquam. Accumsan mi eget adipiscing nulla. Non vestibulum ac interdum condimentum semper commodo massa arcu.</p>
					<div class="row">
						<div class="6u 12u(mobilep)">
							<h3>And now a subheading</h3>
							<p>Adipiscing faucibus nunc placerat. Tempus adipiscing turpis non blandit accumsan eget lacinia nunc integer interdum amet aliquam ut orci non col ut ut praesent. Semper amet interdum mi. Phasellus enim laoreet ac ac commodo faucibus faucibus. Curae lorem ipsum adipiscing ac. Vivamus ornare laoreet odio vis praesent.</p>
						</div>
						<div class="6u 12u(mobilep)">
							<h3>And another subheading</h3>
							<p>Adipiscing faucibus nunc placerat. Tempus adipiscing turpis non blandit accumsan eget lacinia nunc integer interdum amet aliquam ut orci non col ut ut praesent. Semper amet interdum mi. Phasellus enim laoreet ac ac commodo faucibus faucibus. Curae lorem ipsum adipiscing ac. Vivamus ornare laoreet odio vis praesent.</p>
						</div>
					</div>
				</div>
			</section>

{% endblock %}

templates/flights/home.html
{% extends 'flights/base.html' %}
{% block content %}
    <body class="landing" xmlns="http://www.w3.org/1999/html">

		<!-- Banner -->
			<section id="banner">
				<h2>Alpha</h2>
				<p>Another fine responsive site template freebie by HTML5 UP.</p>
				<ul class="actions">
					<li><a href="#" class="button special">Sign Up</a></li>
					<li><a href="#" class="button">Learn More</a></li>
				</ul>
			</section>

		<!-- Main -->
			<section id="main" class="container">

				<section class="box special">
					<header class="major">
						<h2>Introducing Passport Fridays
						<br />
						Weekends are made for enjoying</h2>
						<p>We aim to find you the best flights for a weekend getaway<br />
						All the flights on our website leave Friday after work and return on Sunday night</p>
					</header>
					<!--<span class="image featured"><img src="/static/images/new_york.jpg" alt="" /></span>-->
				</section>
    <section class="box">
    {%  for slice in slices %}
                <div>
                    <p>{{ slice.origin }} to {{ slice.destination }}</p>
                    <p>From {{ slice.dates.departure_date }} to {{ slice.dates.return_date }}</p>
                    <p>{{ slice.price }}</p>
                    <hr>
                </div>
    {% endfor %}
    </section>

        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    </section>
{% endblock %}

templates/flights/index.html
{% extends 'flights/base.html' %}
{% block content %}
<!DOCTYPE HTML>
<!--
	Alpha by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->

	<body class="landing">

		<!-- Banner -->
			<section id="banner">
				<h2>Alpha</h2>
				<p>Another fine responsive site template freebie by HTML5 UP.</p>
				<ul class="actions">
					<li><a href="#" class="button special">Sign Up</a></li>
					<li><a href="#" class="button">Learn More</a></li>
				</ul>
			</section>

		<!-- Main -->
			<section id="main" class="container">

				<section class="box special">
					<header class="major">
						<h2>Introducing the ultimate mobile app
						<br />
						for doing stuff with your phone</h2>
						<p>Blandit varius ut praesent nascetur eu penatibus nisi risus faucibus nunc ornare<br />
						adipiscing nunc adipiscing. Condimentum turpis massa.</p>
					</header>
					<span class="image featured"><img src="/project_static/images/new_york.jpg" alt="" /></span>
				</section>

				<section class="box special features">
					<div class="features-row">
						<section>
							<span class="icon major fa-bolt accent2"></span>
							<h3>Magna etiam</h3>
							<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
						</section>
						<section>
							<span class="icon major fa-area-chart accent3"></span>
							<h3>Ipsum dolor</h3>
							<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
						</section>
					</div>
					<div class="features-row">
						<section>
							<span class="icon major fa-cloud accent4"></span>
							<h3>Sed feugiat</h3>
							<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
						</section>
						<section>
							<span class="icon major fa-lock accent5"></span>
							<h3>Enim phasellus</h3>
							<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
						</section>
					</div>
				</section>

				<div class="row">
					<div class="6u 12u(narrower)">

						<section class="box special">
							<span class="image featured"><img src="images/pic02.jpg" alt="" /></span>
							<h3>Sed lorem adipiscing</h3>
							<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
							<ul class="actions">
								<li><a href="#" class="button alt">Learn More</a></li>
							</ul>
						</section>

					</div>
					<div class="6u 12u(narrower)">

						<section class="box special">
							<span class="image featured"><img src="images/pic03.jpg" alt="" /></span>
							<h3>Accumsan integer</h3>
							<p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
							<ul class="actions">
								<li><a href="#" class="button alt">Learn More</a></li>
							</ul>
						</section>

					</div>
				</div>

			</section>

		<!-- CTA -->
			<section id="cta">

				<h2>Sign up for beta access</h2>
				<p>Blandit varius ut praesent nascetur eu penatibus nisi risus faucibus nunc.</p>

				<form>
					<div class="row uniform 50%">
						<div class="8u 12u(mobilep)">
							<input type="email" name="email" id="email" placeholder="Email Address" />
						</div>
						<div class="4u 12u(mobilep)">
							<input type="submit" value="Sign Up" class="fit" />
						</div>
					</div>
				</form>

			</section>
</html>
{% endblock %}

templates/flights/signin.html
{% extends 'flights/base.html' %}
{% block content %}

		<!-- Main -->
			<section id="main" class="container 75%">
				<header>
					<h2>Contact Us</h2>
					<p>Tell us what you think about our little operation.</p>
				</header>
				<div class="box">
					<form method="post" action="#">{% csrf_token %}
						<!--<div class="row uniform 50%">
							<div class="6u 12u(mobilep)">
								<input type="text" name="name" id="id_name" value="" placeholder="Name" />
							</div>
							<div class="6u 12u(mobilep)">
								<input type="email" name="email" id="id_email" value="" placeholder="Email" />
							</div>
						</div>
						<div class="row uniform 50%">
							<div class="12u">
								<input type="text" name="subject" id="id_subject" value="" placeholder="Subject" />
							</div>
						</div>
						<div class="row uniform 50%">
							<div class="12u">
								<textarea name="message" id="id_message" placeholder="Enter your message" rows="6" ></textarea>
							</div>
						</div>-->
                        {{ form.as_p }}
						<div class="row uniform">
							<div class="12u">
								<ul class="actions align-center">
									<li><input type="submit" value="Send Message" /></li>
								</ul>
							</div>
                            <div class="12u">
                                <p>Dont have a account?</p>
								<ul class="actions align-center">
                                    <li><a href="/signup" type="submit">Sign Up</a> </li>
								</ul>
							</div>
						</div>
					</form>
				</div>
			</section>

{% endblock %}

templates/flights/signup.html
{% extends 'flights/base.html' %}
{% block content %}


		<!-- Main -->
			<section id="main" class="container 75%">
				<header>
					<h2>Contact Us</h2>
					<p>Tell us what you think about our little operation.</p>
				</header>
				<div class="box">
					<form method="post" action="#">{% csrf_token %}
						<!--<div class="row uniform 50%">
							<div class="6u 12u(mobilep)">
								<input type="text" name="name" id="id_name" value="" placeholder="Name" />
							</div>
							<div class="6u 12u(mobilep)">
								<input type="email" name="email" id="id_email" value="" placeholder="Email" />
							</div>
						</div>
						<div class="row uniform 50%">
							<div class="12u">
								<input type="text" name="subject" id="id_subject" value="" placeholder="Subject" />
							</div>
						</div>
						<div class="row uniform 50%">
							<div class="12u">
								<textarea name="message" id="id_message" placeholder="Enter your message" rows="6" ></textarea>
							</div>
						</div>
						<div class="row uniform">-->
                        {{ form.as_p }}
							<div class="12u">
								<ul class="actions align-center">
									<li><input type="submit" value="Send Message" /></li>
								</ul>
							</div>
						</div>
					</form>
				</div>
			</section>

{% endblock %}